url: https://www.newyorkconservative.com
name: New York Conservative
description: '&quot;The day of the Lord will come like a thief, and on that day the heavens will pass away with great violence.&quot; - 2 Peter 3:10'
